### ISSUE TITLE
Handle <object tag 

### ISSUE THREAD

**Issue by Helmut-Ortmann** [kannan-ar/MariGold.OpenXHTML#2]
Hello,

great converter!

Is it possible to also support the '<object' tag like:

- <object width="400" height="400" data="helloworld.swf"></object>

Background: I want to convert ReqIF XHTML tags, and they often use <object tags. They usually do it for images but also for other kinds of binary objects.

Thanks a lot,

Helmut

**Comment by kannan-ar** [comment]
Thank you Helmut. My pleasure to support you. Can you please post a sample HTML snippet? So that I can write a unit test against that.

EDIT: I got it. I assume you need to insert an swf file or image through an object tag. Instead of HTML snippet, can you please send me a sample word document which embed your swf file? You can send the file to marigoldframework[at]gmail[dot]com
